<center><img src="https://i.imgur.com/zRrFdsf.png" width="700"></center>

<a target="_blank" href="https://colab.research.google.com/github/CienciaDeDatosEspacial/TheThematics/blob/main/index.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Mapas tematicos

In [7]:
import geopandas as gpd
linkGit = 'https://github.com/a20242927-alt/Tarea_individual1/raw/main/'
linkWorldMaps = 'worldMaps.gpkg'

we can easily find out the layers in that geopackage file (**worldMaps.gpkg**):

In [8]:
gpd.list_layers(linkGit+linkWorldMaps)

        name    geometry_type
0     rivers  MultiLineString
1     cities            Point
2  countries     MultiPolygon

For the thematics we will retrieve only one layer (map):

In [9]:
countries=gpd.read_file(linkGit+linkWorldMaps,layer='countries')

# see some
countries

                   COUNTRY                                           geometry
0      Aruba (Netherlands)  MULTIPOLYGON (((-69.88223 12.41111, -69.94695 ...
1      Antigua and Barbuda  MULTIPOLYGON (((-61.73889 17.54055, -61.75195 ...
2              Afghanistan  MULTIPOLYGON (((61.27656 35.60725, 61.29638 35...
3                  Algeria  MULTIPOLYGON (((-5.15213 30.18047, -5.13917 30...
4               Azerbaijan  MULTIPOLYGON (((46.54037 38.87559, 46.49554 38...
..                     ...                                                ...
247            South Sudan  MULTIPOLYGON (((34.21807 9.96458, 34.20722 9.9...
248              Indonesia  MULTIPOLYGON (((123.21846 -10.80917, 123.19832...
249             East Timor  MULTIPOLYGON (((124.41824 -9.3001, 124.40446 -...
250  Curacao (Netherlands)  MULTIPOLYGON (((-68.96556 12.19889, -68.91196 ...
251  Bonaire (Netherlands)  MULTIPOLYGON (((-68.19736 12.22264, -68.19292 ...

[252 rows x 2 columns]

Abrimos el dataframe "Somedata" para ello importamos pandas y unimos el link del archivo a Github

In [11]:
import pandas as pd

someDataLink='some_dataworld.csv'
someData=pd.read_csv(linkGit+someDataLink)

## data available
someData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       172 non-null    object
 1   iso2          171 non-null    object
 2   iso3          172 non-null    object
 3   region        172 non-null    object
 4   fragility     172 non-null    float64
 5   co2           172 non-null    int64
 6   sq_km         172 non-null    int64
 7   num_airports  172 non-null    int64
 8   population    172 non-null    int64
 9   mobiles       172 non-null    int64
dtypes: float64(1), int64(5), object(4)
memory usage: 13.6+ KB

## Pre Processing: Merging

Trabajaremos con la variable mobiles asociada al número total de supscriptores de telefonia.

In [12]:
someData.head()

,Country,iso2,iso3,region,fragility,co2,sq_km,num_airports,population,mobiles
0,AFGHANISTAN,AF,AFG,SOUTH ASIA,105.0,7893000,652230,68,40121552,23000000
1,ALBANIA,AL,ALB,EUROPE,58.9,3794000,28748,3,3107100,2610000
2,ALGERIA,DZ,DZA,AFRICA,75.4,151633000,2381740,95,47022473,51500000
3,ANGOLA,AO,AGO,AFRICA,87.8,19362000,1246700,107,37202061,25700000
4,ANTIGUA AND BARBUDA,AG,ATG,CENTRAL AMERICA AND THE CARIBBEAN,54.4,729000,443,4,102634,184000

Preparing thematic maps requires **social data** _about_ the geometry (line, polygon, point). The object **countries** has no social data, so the preprocessing requires geomerging.

### Geo Merging

Ahora debemos incluir los datos de mobiles con el país correspondiente.Para ello los nombres de los países deben coindir.

In [13]:
countries.COUNTRY.head()

0    Aruba (Netherlands)
1    Antigua and Barbuda
2            Afghanistan
3                Algeria
4             Azerbaijan
Name: COUNTRY, dtype: object

In [14]:
someData.Country.head()

0            AFGHANISTAN
1                ALBANIA
2                ALGERIA
3                 ANGOLA
4    ANTIGUA AND BARBUDA
Name: Country, dtype: object

Renombramos el nombre de la variable paises para que tanto en el GTF y DTF sea el mismo.

In [15]:
countries.rename(columns={'COUNTRY':'Country'},inplace=True)

Convertimos a mayuscula los datos ya que en el GTF los países estan en minuscula y puede hacer que no coincidan.

In [16]:
countries['Country']=countries.Country.str.upper()

Verificamos que datos no comparten.Para ello en onlyDF obtenemos los datos que faltan en el GDF y en onlyGDF los que faltan en DF

In [17]:
onlyDF=set(someData.Country)- set(countries.Country)
onlyGDF=set(countries.Country)- set(someData.Country)

Check here:

In [18]:
onlyDF

{'BAHAMAS (THE)',
 'BOLIVIA (PLURINATIONAL STATE OF)',
 'BRUNEI DARUSSALAM',
 'CABO VERDE',
 'CENTRAL AFRICAN REPUBLIC (THE)',
 'COMOROS (THE)',
 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
 'CONGO (THE)',
 "CÔTE D'IVOIRE",
 'DOMINICAN REPUBLIC (THE)',
 'ESWATINI',
 'GAMBIA (THE)',
 'IRAN (ISLAMIC REPUBLIC OF)',
 'KOREA (THE REPUBLIC OF)',
 "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
 'MICRONESIA (FEDERATED STATES OF)',
 'MOLDOVA (THE REPUBLIC OF)',
 'NETHERLANDS (THE)',
 'NIGER (THE)',
 'NORTH MACEDONIA',
 'NORTHERN MARIANA ISLANDS (THE)',
 'PHILIPPINES (THE)',
 'RUSSIAN FEDERATION (THE)',
 'SAMOA',
 'SUDAN (THE)',
 'TANZANIA, THE UNITED REPUBLIC OF',
 'TIMOR-LESTE',
 'UNITED ARAB EMIRATES (THE)',
 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
 'UNITED STATES OF AMERICA (THE)'}

In [26]:
onlyGDF

{'AMERICAN SAMOA (US)',
 'AMERICAN VIRGIN ISLANDS (US)',
 'ANDORRA',
 'ANGUILLA (UK)',
 'ANTARCTICA',
 'ARUBA (NETHERLANDS)',
 'BAHAMAS',
 'BAKER ISLAND (US)',
 'BERMUDA (UK)',
 'BOLIVIA',
 'BONAIRE (NETHERLANDS)',
 'BOUVET ISLAND (NORWAY)',
 'BRITISH INDIAN OCEAN TERRITORY (UK)',
 'BRITISH VIRGIN ISLANDS(UK)',
 'BRUNEI',
 'CAPE VERDE',
 'CAYMAN ISLANDS (UK)',
 'CENTRAL AFRICAN REPUBLIC',
 'CHRISTMAS ISLAND (AUSTRALIA)',
 'COCOS (KEELING) ISLANDS (AUSTRALIA)',
 'COMOROS',
 'CONGO',
 'COOK ISLANDS (NEW ZEALAND)',
 'CURACAO (NETHERLANDS)',
 'CZECH REPUBLIC',
 'DEMOCRATIC REPUBLIC OF THE CONGO',
 'DOMINICA',
 'DOMINICAN REPUBLIC',
 'EAST TIMOR',
 'ERITREA',
 'FALKLAND ISLANDS (UK)',
 'FAROE ISLANDS (DENMARK)',
 'FEDERATED STATES OF MICRONESIA',
 'FRENCH GUIANA (FRANCE)',
 'FRENCH POLYNESIA (FRANCE)',
 'FRENCH SOUTHERN & ANTARCTIC LANDS (FRANCE)',
 'GAMBIA',
 'GIBRALTAR (UK)',
 'GLORIOSO ISLANDS (FRANCE)',
 'GREENLAND (DENMARK)',
 'GUADELOUPE (FRANCE)',
 'GUAM (US)',
 'GUERNSEY (UK)',
 'HEARD ISLAND & MCDONALD ISLANDS (AUSTRALIA)',
 'HOWLAND ISLAND (US)',
 'IRAN',
 'ISLE OF MAN (UK)',
 'IVORY COAST',
 'JAN MAYEN (NORWAY)',
 'JARVIS ISLAND (US)',
 'JERSEY (UK)',
 'JOHNSTON ATOLL (US)',
 'JUAN DE NOVA ISLAND (FRANCE)',
 'KIRIBATI',
 'LAOS',
 'LIECHTENSTEIN',
 'MACEDONIA',
 'MARSHALL ISLANDS',
 'MARTINIQUE (FRANCE)',
 'MAYOTTE (FRANCE)',
 'MIDWAY ISLANDS (US)',
 'MOLDOVA',
 'MONACO',
 'MONTSERRAT (UK)',
 'MYANMAR',
 'NAURU',
 'NETHERLANDS',
 'NEW CALEDONIA (FRANCE)',
 'NIGER',
 'NIUE (NEW ZEALAND)',
 'NORFOLK ISLAND (AUSTRALIA)',
 'NORTH KOREA',
 'NORTHERN MARIANA ISLANDS (US)',
 'PALAU (US)',
 'PALESTINE',
 'PARACEL ISLANDS (CHINA)',
 'PHILIPPINES',
 'PITCAIRN ISLANDS (UK)',
 'PUERTO RICO (US)',
 'REUNION (FRANCE)',
 'RUSSIA',
 'SAN MARINO',
 'SLOVAKIA',
 'SOMALIA',
 'SOUTH GEORGIA AND THE SOUTH SANDWICH IS (UK)',
 'SOUTH KOREA',
 'SPRATLY ISLANDS (DISPUTED)',
 'ST. HELENA (UK)',
 'ST. KITTS AND NEVIS',
 'ST. LUCIA',
 'ST. PIERRE AND MIQUELON (FRANCE)',
 'ST. VINCENT AND THE GRENADINES',
 'SUDAN',
 'SVALBARD (NORWAY)',
 'SWAZILAND',
 'SYRIA',
 'TAIWAN',
 'TANZANIA',
 'TOKELAU (NEW ZEALAND)',
 'TONGA',
 'TURKS AND CAICOS ISLANDS (UK)',
 'TUVALU',
 'UNITED ARAB EMIRATES',
 'UNITED KINGDOM',
 'UNITED STATES',
 'VANUATU',
 'WAKE ISLAND (US)',
 'WALLIS AND FUTUNA (FRANCE)',
 'WESTERN SAHARA',
 'WESTERN SAMOA'}

There are several countries in the DF that did not find a match in the GDF (map). Of course, most of them are in the map, let's see why they were not matched.

### Fuzzy merging

Utilizamos la libreria de python thefuzz para analizar grado de similitud en los textos.

In [22]:
 !pip install thefuzz

Collecting thefuzz
  Downloading thefuzz-0.22.1-py3-none-any.whl.metadata (3.9 kB)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from thefuzz)
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading thefuzz-0.22.1-py3-none-any.whl (8.2 kB)
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 32.8 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, thefuzz
Successfully installed rapidfuzz-3.14.6 thefuzz-0.22.1

*Para cada país que solo esta en el DF buscamos las mejores coindicendias de los que solo estaban en el GDF*

In [27]:
from thefuzz.process import extractOne as best

In [32]:

[(country, best(country,onlyGDF)[0],best(country,onlyGDF)[1]) for country in onlyDF]

[('TIMOR-LESTE', 'EAST TIMOR', 81),
 ('NETHERLANDS (THE)', 'NETHERLANDS', 95),
 ('DOMINICAN REPUBLIC (THE)', 'DOMINICAN REPUBLIC', 95),
 ('CENTRAL AFRICAN REPUBLIC (THE)', 'CENTRAL AFRICAN REPUBLIC', 95),
 ('NIGER (THE)', 'NIGER', 90),
 ('MICRONESIA (FEDERATED STATES OF)', 'FEDERATED STATES OF MICRONESIA', 95),
 ('NORTHERN MARIANA ISLANDS (THE)', 'NORTHERN MARIANA ISLANDS (US)', 91),
 ('KOREA (THE REPUBLIC OF)', 'NORTH KOREA', 86),
 ('BRUNEI DARUSSALAM', 'BRUNEI', 90),
 ('UNITED STATES OF AMERICA (THE)', 'UNITED STATES', 90),
 ('NORTH MACEDONIA', 'MACEDONIA', 90),
 ('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
  'UNITED KINGDOM',
  90),
 ('IRAN (ISLAMIC REPUBLIC OF)', 'IRAN', 90),
 ('PHILIPPINES (THE)', 'PHILIPPINES', 95),
 ('BAHAMAS (THE)', 'BAHAMAS', 90),
 ('CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
  'DEMOCRATIC REPUBLIC OF THE CONGO',
  95),
 ("LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)", 'CENTRAL AFRICAN REPUBLIC', 86),
 ('UNITED ARAB EMIRATES (THE)', 'UNITED ARAB EMIRATES', 95),
 ('SUDAN (THE)', 'SUDAN', 90),
 ('RUSSIAN FEDERATION (THE)', 'RUSSIA', 90),
 ('CONGO (THE)', 'CONGO', 90),
 ('MOLDOVA (THE REPUBLIC OF)', 'MOLDOVA', 90),
 ('TANZANIA, THE UNITED REPUBLIC OF', 'TANZANIA', 90),
 ("CÔTE D'IVOIRE", 'IVORY COAST', 58),
 ('COMOROS (THE)', 'COMOROS', 90),
 ('ESWATINI', 'MARTINIQUE (FRANCE)', 60),
 ('SAMOA', 'WESTERN SAMOA', 90),
 ('BOLIVIA (PLURINATIONAL STATE OF)', 'BOLIVIA', 90),
 ('GAMBIA (THE)', 'GAMBIA', 90),
 ('CABO VERDE', 'CAPE VERDE', 80)]

In [30]:
pd.DataFrame([(country, best(country,onlyGDF)[0],best(country,onlyGDF)[1]) for country in onlyDF])

,0,1,2
0,TIMOR-LESTE,EAST TIMOR,81
1,NETHERLANDS (THE),NETHERLANDS,95
2,DOMINICAN REPUBLIC (THE),DOMINICAN REPUBLIC,95
3,CENTRAL AFRICAN REPUBLIC (THE),CENTRAL AFRICAN REPUBLIC,95
4,NIGER (THE),NIGER,90
5,MICRONESIA (FEDERATED STATES OF),FEDERATED STATES OF MICRONESIA,95
6,NORTHERN MARIANA ISLANDS (THE),NORTHERN MARIANA ISLANDS (US),91
7,KOREA (THE REPUBLIC OF),NORTH KOREA,86
8,BRUNEI DARUSSALAM,BRUNEI,90
9,UNITED STATES OF AMERICA (THE),UNITED STATES,90
10,NORTH MACEDONIA,MACEDONIA,90
11,UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...,UNITED KINGDOM,90
12,IRAN (ISLAMIC REPUBLIC OF),IRAN,90
13,PHILIPPINES (THE),PHILIPPINES,95
14,BAHAMAS (THE),BAHAMAS,90
15,CONGO (THE DEMOCRATIC REPUBLIC OF THE),DEMOCRATIC REPUBLIC OF THE CONGO,95
16,LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE),CENTRAL AFRICAN REPUBLIC,86
17,UNITED ARAB EMIRATES (THE),UNITED ARAB EMIRATES,95
18,SUDAN (THE),SUDAN,90
19,RUSSIAN FEDERATION (THE),RUSSIA,90
20,CONGO (THE),CONGO,90
21,MOLDOVA (THE REPUBLIC OF),MOLDOVA,90
22,"TANZANIA, THE UNITED REPUBLIC OF",TANZANIA,90
23,CÔTE D'IVOIRE,IVORY COAST,58
24,COMOROS (THE),COMOROS,90
25,ESWATINI,MARTINIQUE (FRANCE),60
26,SAMOA,WESTERN SAMOA,90
27,BOLIVIA (PLURINATIONAL STATE OF),BOLIVIA,90
28,GAMBIA (THE),GAMBIA,90
29,CABO VERDE,CAPE VERDE,80

Let's sort by the column '2' (the third):

In [29]:
pd.DataFrame([(country, best(country,onlyGDF)[0],best(country,onlyGDF)[1]) for country in onlyDF]).sort_values(by=2)

,0,1,2
23,CÔTE D'IVOIRE,IVORY COAST,58
25,ESWATINI,MARTINIQUE (FRANCE),60
29,CABO VERDE,CAPE VERDE,80
0,TIMOR-LESTE,EAST TIMOR,81
16,LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE),CENTRAL AFRICAN REPUBLIC,86
7,KOREA (THE REPUBLIC OF),NORTH KOREA,86
4,NIGER (THE),NIGER,90
12,IRAN (ISLAMIC REPUBLIC OF),IRAN,90
14,BAHAMAS (THE),BAHAMAS,90
19,RUSSIAN FEDERATION (THE),RUSSIA,90
20,CONGO (THE),CONGO,90
21,MOLDOVA (THE REPUBLIC OF),MOLDOVA,90
11,UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...,UNITED KINGDOM,90
10,NORTH MACEDONIA,MACEDONIA,90
9,UNITED STATES OF AMERICA (THE),UNITED STATES,90
8,BRUNEI DARUSSALAM,BRUNEI,90
27,BOLIVIA (PLURINATIONAL STATE OF),BOLIVIA,90
22,"TANZANIA, THE UNITED REPUBLIC OF",TANZANIA,90
26,SAMOA,WESTERN SAMOA,90
24,COMOROS (THE),COMOROS,90
28,GAMBIA (THE),GAMBIA,90
18,SUDAN (THE),SUDAN,90
6,NORTHERN MARIANA ISLANDS (THE),NORTHERN MARIANA ISLANDS (US),91
2,DOMINICAN REPUBLIC (THE),DOMINICAN REPUBLIC,95
15,CONGO (THE DEMOCRATIC REPUBLIC OF THE),DEMOCRATIC REPUBLIC OF THE CONGO,95
13,PHILIPPINES (THE),PHILIPPINES,95
1,NETHERLANDS (THE),NETHERLANDS,95
5,MICRONESIA (FEDERATED STATES OF),FEDERATED STATES OF MICRONESIA,95
3,CENTRAL AFRICAN REPUBLIC (THE),CENTRAL AFRICAN REPUBLIC,95
17,UNITED ARAB EMIRATES (THE),UNITED ARAB EMIRATES,95

De los resultados, consideramos los bajos números de similitud para hacer cambios manuales:
* **COTE D'IVOIRE** si es *Ivory Coast*
* **ESWATINI** también es *SWAZILAND*.
* **KOREA (THE REPUBLIC OF)** is not _NORTH KOREA_.
* **LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)** is too long to match *LAOS* (if it exists in the map like that).

In [33]:
countries.Country[countries.Country.str.contains('SWAZ|LAO|KORE')]

120                               NORTH KOREA
122                   KOREA (THE REPUBLIC OF)
126    LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)
Name: Country, dtype: object

Then, it makes sense to change those manually (notice the 'replace' uses Python dictionaries):

In [31]:
# this is a {dictionary}

manualChanges={'SWAZILAND':'ESWATINI',
               'LAOS':"LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
               'SOUTH KOREA':'KOREA (THE REPUBLIC OF)'
              }

countries.replace(to_replace={'Country':manualChanges},inplace=True)

At this stage, we should recompute the differences:

In [ ]:
# updating
onlyDF=set(someData.Country)- set(countries.Country)
onlyGDF=set(countries.Country)- set(someData.Country)

An re run this code:

In [ ]:
# keeping high scores

pd.DataFrame([(country, best(country,onlyGDF)[0],best(country,onlyGDF)[1]) for country in onlyDF]).sort_values(2)

All this is correct now!

Let's prepare the changes:

In [ ]:
# new {dictionary}
changesToDF={country: best(country,onlyGDF)[0] for country in onlyDF}
changesToDF

In [ ]:
someData.replace(to_replace={'Country':changesToDF},inplace=True)

What is left to match?

In [ ]:
# updating
onlyDF=set(someData.Country)- set(countries.Country)
onlyGDF=set(countries.Country)- set(someData.Country)
[(country, best(country,onlyGDF)) for country in onlyDF]

Once you are here, merging can proceed:

In [ ]:
## GDF to the 'left'
theMapAndData=countries.merge(someData, on='Country')

And our GDF has social data now!

In [ ]:
theMapAndData.info()

We should save this map of countries and their indicators in a new file:

In [ ]:
theMapAndData.to_file("worldindicators.json")

# Thematics: the DDM (Dot Density Map)

You have a DDM if you use dot to show comparatively which polygon of a map has 'more' (or 'less') of some countable phenomenon of interest.
A dot is an aggregated value, but it is constant for each dot.

We have the world map, let's keep Africa:

In [ ]:
theMapAndData.region.value_counts()

### Preprocessing: Filtering

In [ ]:
# then

Africa=theMapAndData[theMapAndData.region=='AFRICA']
Africa.plot()

A DDM can serve as an effective way to show the distribution of people. The most critical tasks are:

* Dot Placement: The dots should be randomly distributed within each polygon to avoid misrepresenting the data.

* Dot Unit: Deciding how many people each dot should represent is key for visual clarity. This value should be chosen carefully to avoid oversaturation or sparsity.

The size of all dots on the map must be the same to ensure a consistent visual comparison.

### Preprocessing: aggregating

This is a DOT UNIT proposal:

In [ ]:
justDots=Africa.copy()
dot_value = 100000
justDots['num_dots'] = (justDots['population'] / dot_value).astype(int)

### Preprocessing: distributing dots

And here, we get a location for the dots:

In [ ]:
# 2. Generate the random dot locations using .sample_points()
justDots = justDots.sample_points(size=justDots['num_dots']).explode(index_parts=True)

You get this:

In [ ]:
justDots

In [ ]:
# what is it?
type(justDots)

### Preprocessing: building GDF from GS

Notice the multi index (MI), one for a country and for a dot. As we are planing to send these points to R, we avoid MI:

In [ ]:
justDots.reset_index(drop=True, inplace=True)
Africa_dots=gpd.GeoDataFrame(geometry=justDots)
Africa_dots

Now you have a GDF:

In [ ]:
Africa_dots.info()

Juts plot the polygons as the base, and the points as the layer on top!

In [ ]:
base=Africa.plot(facecolor="white",#color of polygon fill
               edgecolor='grey') #color of border
Africa_dots.plot(markersize=0.05, color='red',ax=base)

It is generally recommended that DDMs use an **equal-area projection**, which benefits density and limits area distortion.

In [ ]:
base=Africa.to_crs(8857).plot(facecolor="white",
                              edgecolor='grey')
Africa_dots.to_crs(8857).plot(markersize=0.05, color='red',ax=base)

Let's keep the continent countries with that crs:

In [ ]:
Africa_8857=Africa.to_crs(8857)
Africa_dots_8857=Africa_dots.to_crs(8857)

# Thematics: the PSM (Proportional Symbol Map)

You have a PSM if you use a symbol (generally a circle) to show the distribution of a variable per location.
The symbol is an aggregated raw value, and its size varies according to those values. So now we need:

### Preprocessing: GDF of centroids

1. A location for a symbol, generally the polygon centroid.

In [ ]:
Africa_8857_centroids = Africa_8857.copy()

# Africa_8857_centroids will have a new geometry:
Africa_8857_centroids['geometry'] = Africa_8857_centroids['geometry'].centroid

2. A size of varying values (not constant as in DDMs). Let's use population again.

In [ ]:
Africa_8857_centroids['size'] = Africa_8857_centroids['population'].apply(lambda x: x**0.5/100)

## or
# import numpy as np
# Africa_8857_centroids['size'] = Africa_8857_centroids['population'].apply(lambda x: np.log10(x))

We got the basics, then:

In [ ]:
base=Africa_8857.plot(facecolor="white",
                      edgecolor='grey')
# Plot the centroids on top
Africa_8857_centroids.plot(
    ax=base,
    markersize=Africa_8857_centroids['size'],
    color='grey'
)

Keep in mind that the standard way of computing centroids may bring some trouble. Let´s plot Seychelles:

In [ ]:
base=Africa_8857[Africa_8857.Country=="SEYCHELLES"].explore()
Africa_8857_centroids[Africa_8857_centroids.Country=="SEYCHELLES"].explore(m=base,color="red")

A good alternative to centroids is representative_point() when dealing with complex multipolygons.

In [ ]:
# replace the points
Africa_8857_centroids["geometry"]=Africa_8857.representative_point()

We will keep that last result.

In [ ]:
base=Africa_8857[Africa_8857.Country=="SEYCHELLES"].explore()
Africa_8857_centroids[Africa_8857_centroids.Country=="SEYCHELLES"].explore(m=base,color="red")

### Preprocessing: Computing new columns

PPMs are not thematic maps to see precise values, but to reveal clear differences on the variable distribution used. As, human eyes are very limited to detect area differences, we may need to use some other tactics to help uncover some patterns.

For example, let's confirm if we have outliers:

In [ ]:
boxplotInfo=Africa_8857_centroids.boxplot(column='population',return_type="dict")

The object **boxplotInfo** showed the boxplot, and we confirm there are outliers. We can recover them like this:

In [ ]:
outliers=boxplotInfo['fliers'][0].get_ydata()
## see
outliers

Then, these are the outlying countries:

In [ ]:
Africa_8857_centroids[Africa_8857_centroids.population.isin(outliers)]

Knowing this information, we can create a column as outlier flag:

In [ ]:
Africa_8857_centroids['population_outlier']=Africa_8857_centroids.population.isin(outliers)*1

## see
Africa_8857_centroids

We can use that like this:

In [ ]:
base = Africa_8857.plot(color='white', edgecolor='black', figsize=(10,10))

# Define your color map
mapcolor = {1: 'black', 0: 'lightgrey'}

# Plot the centroids on top
Africa_8857_centroids.plot(
    ax=base,
    markersize=Africa_8857_centroids['size'],
    color=Africa_8857_centroids['population_outlier'].map(mapcolor)
)

Here, we do a good job for outliers, but it is difficult to interprete the other ones. We could use some redundancy, but more work is needed:
1. Create two maps of centroids:

In [ ]:
# Create explicit copies of the DataFrames
Africa_8857_centroids_out = Africa_8857_centroids[Africa_8857_centroids.population_outlier==1].copy()
Africa_8857_centroids_no_out = Africa_8857_centroids[Africa_8857_centroids.population_outlier==0].copy()

2. Compute sizes in each:

In [ ]:
Africa_8857_centroids_out['size'] = Africa_8857_centroids_out['population'].apply(lambda x: x**0.5 / 50)
Africa_8857_centroids_no_out['size'] = Africa_8857_centroids_no_out['population'].apply(lambda x: x**0.5 / 50)

Now, plot the three layers, using some color gradient for the non-outliers:

In [ ]:
base=Africa_8857.plot(color='white', edgecolor='grey',figsize=(10,10))

Africa_8857_centroids_no_out.plot(
    ax=base,
    markersize=Africa_8857_centroids_no_out['size'],
    edgecolor='grey',
    c=Africa_8857_centroids_no_out['size'],
    cmap='Blues_r'
)
Africa_8857_centroids_out.plot(
    ax=base,
    markersize=Africa_8857_centroids_out['size'],
    color='orange'
)

# Thematics: Choropleths

Notice that the DDMs may use aggregated counts, and the PSMs use the variables in its original form. Choropleths will 'paint' the whole polygon and as noticed in PSMs, we have to be very careful when using color in shape, as the area itself is a confounding. To control this visual artifact, the variable must be normalized, that is, divided by a value correlated with the area.

Then, for this course, a choropleth is a normalized representation of data.

Following our definition:

* This is **NOT** a choropleth:

In [ ]:
Africa_8857.plot(Africa_8857.population)

* This **IS** a choropleth:

In [ ]:
Africa_8857.plot(Africa_8857.population/Africa_8857.sq_km)

Choropleths are great to represent normalized indicators such as:
* Densities
* Ratios
* Rates
* Averages

Population by area is a density indicator. This is a real number (not an integer), so most of the time the color gradient might  not be
that useful to reveal some pattern visually. Then, we often discretize (or bin) the indicator computed.

### Preprocessing: Discretizing

Now, we want to cut the variable. Run the next code to make sure you have tose packages:

In [ ]:
## do you have these installed?
# ! pip show numba mapclassify numpy

We will discretize this:

In [ ]:
Africa_8857['population_density']=Africa_8857.population/Africa_8857.sq_km

Let's explore the bining algorithms:

In [ ]:
import mapclassify
import numpy as np

np.random.seed(12345) # so we all get the same results!

# let's try 5 intervals
K=5
theVar=Africa_8857['population_density']
# same interval width, easy interpretation
ei5 = mapclassify.EqualInterval(theVar, k=K)
# same interval width based on standard deviation, easy - but not as the previous one, poor when high skewness
msd = mapclassify.StdMean(theVar)
# interval width varies, counts per interval are close, not easy to grasp, repeated values complicate cuts
q5=mapclassify.Quantiles(theVar,k=K)

# based on similarity, good for multimodal data
mb5 = mapclassify.MaximumBreaks(theVar, k=K)
# based on similarity, good for skewed data
ht = mapclassify.HeadTailBreaks(theVar) # no K needed
# based on similarity, optimizer
fj5 = mapclassify.FisherJenks(theVar, k=K)
# based on similarity, optimizer
jc5 = mapclassify.JenksCaspall(theVar, k=K)
# based on similarity, optimizer
mp5 = mapclassify.MaxP(theVar, k=K)

How can we select the right classification?
Let me use the the Absolute deviation around class median (ADCM) to make the comparisson:

In [ ]:
class5 = ei5,msd, q5,mb5,  ht, fj5, jc5, mp5
# Collect ADCM for each classifier
fits = np.array([ c.adcm for c in class5])
# Convert ADCM scores to a DataFrame
adcms = pd.DataFrame(fits)
# Add classifier names
adcms['classifier'] = [c.name for c in class5]
# Add column names to the ADCM
adcms.columns = ['ADCM', 'Classifier']

Now, plot the **adcms**:

In [ ]:
adcms.sort_values('ADCM').plot.barh(x='Classifier')

Let's save the best strategy:

In [ ]:
Africa_8857['population_density_FJ5'] = fj5.yb

In [ ]:
# there you are
Africa_8857[['population_density','population_density_FJ5']].head(20)

We could create a copy of the bins to add labels:

In [ ]:
# renaming
newLabelsForLevels={0:"0_VeryLow", 1:"1_Low", 2:"2_Middle", 3:"3_High", 4:"4_VeryHigh"}

Africa_8857['population_density_FJ5_cat']=Africa_8857.loc[:,'population_density_FJ5'].replace(newLabelsForLevels)

# we have
Africa_8857[['population_density','population_density_FJ5','population_density_FJ5_cat']].head(20)

We are ready for a discrete choropleth:

In [ ]:
import matplotlib.pyplot as plt

f, ax = plt.subplots(1, figsize=(10, 10))
Africa_8857.plot(column='population_density_FJ5_cat', # variable to plot
                 cmap='viridis_r', # set of colors
                 categorical=True, # can be interpreted as category
                 edgecolor='grey', # border color
                 linewidth=0.3, # width of border
                 legend=True, # need a legend?
                 ax=ax
       )

ax.set_axis_off()

# Saving

Let's save this maps for R.

In [ ]:
## Good practice to refresh your memory

## Find only GeoDataFrames in the current session
geodataframe_list = [var for var in globals() if isinstance(globals()[var], gpd.GeoDataFrame)]

print("List of GeoDataFrames in memory:")
for name in geodataframe_list:
    print(name)

These are the ones needed in R:

In [ ]:
# for choropleth and base map
Africa_8857.info()

In [ ]:
# for DDMs
Africa_dots_8857.info()

In [ ]:
# for PSMs
Africa_8857_centroids.info()

In [ ]:
# for PSMs
Africa_8857_centroids_out.info()

In [ ]:
# for PSMs
Africa_8857_centroids_no_out.info()

The file **africa_8857.gpkg** will keep all those maps as layers!

In [ ]:
Africa_8857.to_file("africa_8857.gpkg",driver='GPKG',layer='continent')
Africa_dots_8857.to_file("africa_8857.gpkg",driver='GPKG',layer='population_ddm')
Africa_8857_centroids.to_file("africa_8857.gpkg",driver='GPKG',layer='population_psm')
Africa_8857_centroids_out.to_file("africa_8857.gpkg",driver='GPKG',layer='outlier_population_psm')
Africa_8857_centroids_no_out.to_file("africa_8857.gpkg",driver='GPKG',layer='no_outlier_population_psm')